import type { Metadata } from "next"
import localFont from "next/font/local"
import "./styles/globals.css"
import { Belanosima } from "next/font/google"
import { Header } from "../lib/components/Header"
import { Footer } from "@/lib/components/Footer"
import CityLayout from "./layouts/CityLayout"

const favoritSans = localFont({
  src: "./fonts/Favorit-Regular.woff",
  variable: "--font-favorit-sans",
  weight: "100 900",
})
const belanosimaSans = Belanosima({
  variable: "--font-belanosima-sans",
  display: "swap",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Polomaps",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // You'll need to implement a way to determine if it's a city page
  const isCityPage = true // This should be dynamically determined based on the current route

  return (
    <html lang="en">
      <body
        className={`${favoritSans.variable} ${belanosimaSans.variable} font-[family-name:var(--font-favorit-sans)] antialiased`}
      >
        {isCityPage ? (
          <CityLayout>{children}</CityLayout>
        ) : (
          <>
            <Header />
            {children}
            <Footer />
          </>
        )}
      </body>
    </html>
  )
}