import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";

const favoritSans = localFont({
  src: "./fonts/Favorit-Regular.woff",
  variable: "--font-favorit-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${favoritSans.variable} font-[family-name:var(--font-favorit-sans)] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
