import type { Metadata } from "next"
import localFont from "next/font/local"
import "./styles/globals.css"
import { Belanosima } from "next/font/google"
import { Header } from "../lib/components/Header"
import { Footer } from "@/lib/components/Footer"

const favoritSans = localFont({
  src: "./fonts/Favorit-Regular.woff",
  variable: "--font-favorit-sans",
  weight: "100 900",
})
const belanosimaSans = Belanosima({
  variable: "--font-belanosima-sans",
  display: "swap",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${favoritSans.variable} ${belanosimaSans.variable} font-[family-name:var(--font-favorit-sans)] antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
